#!/bin/bash

echo "Application is starting..."

default_app_name="Spring"
echo  "Application name is ${default_app_name}"

# 3 type of date
# string ""
# numbers value=25
# massive array=(1 5 22 190 1240 2050)

#      0 1  2  3    4    5
array=(1 5 22 190 1240 2050)
echo "${array[2]}"
# lenght
echo "${array[@]}"
# toString
echo "${#array[@]}"
array[2]=222
echo "${array[@]}"
# add value in the end
array+=(10999 34)
echo "${array[@]}"

echo "Enter application name:"
read app_name

echo "New application name is ${app_name}"

value=-9
# simple if construction
if (( value > 0 )); then
  echo "${value} is positive 1"
fi

# if else construction
if (( value < 0 )); then
    echo "${value} is negative 2"
else
  echo "${value} is positive 2"
fi

# if ifelse construction
if (( value > 0 )); then
  echo "${value} is positive 3"
elif (( value == 0 )); then
  echo "${value} is zero 3"
else
  echo "${value} is negative 3"
fi


echo "Enter any program:"
read program
# case
case "${program}" in
clean)
  echo "Clean is invoked"
  echo ""
  ;;
build)
  echo "Build is invoked"
  ;;
# default
*)
  echo "Default is invoked"
  echo "${program} is not supported by this program"
  exit 2
  ;;
esac